### ISSUE TITLE
Create GitHub Page for easy access to documentation

### ISSUE THREAD

**Issue by marsjaninzmarsa** [facebook/DelegatedRecoverySpecification#1]
You know, github.io and stuff.

Right now directly from browser we can only look at raw HTML...

**Comment by hillbrad** [comment]
Thank you for the suggestion.  We will be adding better browsable documentation soon, but the Facebook open source organization on GitHub is not currently set up to use GitHub Pages.

The raw.txt version should be pretty usable and has all the same information, and you can always download and view the HTML version locally. Apologies for the inconvenience.
